# Generated by Django 5.1.7 on 2025-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
