# Generated by Django 5.1.7 on 2025-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_logentry_end_time_alter_logentry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('visited', 'Visited'), ('skipped', 'Skipped')], default='planned', max_length=20),
        ),
    ]
