# Generated by Django 5.1.7 on 2025-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_stop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='source',
            field=models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
